branch-defaults:
  default:
    environment: imagefilter-chrille-dev
    group_suffix: null
  dev:
    environment: imagefilter-chrille-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: imagefilter-chrille-dev
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: root
  repository: null
  sc: git
  workspace_type: Application
